name: Build and Deployment

on:
  push:
    branches: ["main"]

env:
  AWS_REGION: us-east-1

jobs:
  lamda:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: us-east-1

      - name: Build artifacts
        run: chmod 777 build.sh && ./build.sh

      - name: Copy Artifacts
        run: aws s3 cp serverless.zip s3://${{secrets.S3_BUCKET}}

      - name: Update code
        run: aws lambda update-function-code --function-name serverless --s3-bucket ${{secrets.S3_BUCKET}} --s3-key serverless.zip
